### ISSUE TITLE
add kodiak workflow

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/frontendx#19]
Add `kodiak.yaml` file to configure automerging by kodiak application.

**Comment by cybersiddhu** [comment]
https://github.com/dictyBase/modware-stock/blob/develop/.kodiak.toml

Check this out.
It only automatically merges minor and patch updates while leaving out major ones.

**Comment by ktun95** [comment]
c22f3cb7449e868d4f75c6d33a8be166498c21b7
